### PR TITLE
[#1151] Background syncing

### LINKED ISSUE #634: Wallet synchronisation continues even when app is in background
### Describe the issue
Walet synchronisation is not paused when app is brought to background

#### If so, please list the steps to reproduce below:
1. install app
2. onboard wallet
3. when app is syncing leave the app
4. logcat continues to show sync updates

- App Version: 0.1-debug
- Android Version: 12
- Device: (if applies)

### LINKED ISSUE #1151: Background syncing
The goal is to be able to sync in the background. There are several possible scenarios where each one needs different handling:
- syncing at the time people sleep - the power + wifi are required
- being able to finish some request when going to the background - e.g. when send is initiated and a user doesn't wait until the request is done

All information and investigation outcomes will be gathered in this ticket.

Some form of background syncing was supposedly added back in #191 but I was unaware of it existing. We should check whether it is indeed working in the same way as https://github.com/Electric-Coin-Company/zashi-ios/issues/982 will work, and if not we should bring Zashi Android up to parity (as much as is possible on the Android platform).

### PR DESCRIPTION
**Pull request by HonzaR**
- A periodic background block synchronization has been added. When the device is connected to the internet using an unmetered connection and is plugged into the power, the background task will start to synchronize blocks randomly between 3 and 4 a.m.
- The background worker was in place but not fully working, plus was set to trigger randomly in 24 hours
- Changelog update
- Closes #1151
- Closes #634
- Its follow-up #1249

> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] **Self-review** your own code in GitHub's web interface[^1]
- [ ] Add **automated tests** as appropriate
- [ ] Update the [**manual tests**](../blob/main/docs/testing/manual_testing)[^2] as appropriate
- [ ] Check the **code coverage**[^3] report for the automated tests
- [x] Update **documentation** as appropriate (e.g [**README.md**](../blob/main/README.md), [**Architecture.md**](../blob/main/docs/Architecture.md), [**CHANGELOG.md**](../blob/main/CHANGELOG.md), etc.)
- [x] **Run the app** and try the changes
- [x] Pull in the latest changes from the **main** branch and **squash** your commits before assigning a reviewer[^4]

> **Note**
> It is good practice to provide before and after UI  **screenshots** in the description of this PR. This is only applicable for changes that modify the UI.

# Reviewer

- [x] Check the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) **checklist**
- [ ] Perform an **ad hoc review**[^5]
- [ ] Review the **automated tests**
- [ ] Review the **manual tests**
- [ ] Review the **documentation**, [**README.md**](../blob/main/README.md), [**Architecture.md**](../blob/main/docs/Architecture.md), etc. as appropriate
- [ ] **Run the app** and try the changes[^6]

[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
[^2]: _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed. Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck -PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true` for Android modules._
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
[^5]: _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
[^6]: _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

**Review by LukasKorba — APPROVED** [review]

File: ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt [hunk 1]
```diff
@@ -12,55 +12,115 @@ import cash.z.ecc.android.sdk.Synchronizer
...
         fun newWorkRequest(): PeriodicWorkRequest {
+            val targetTimeDiff = calculateTargetTimeDifference()
+
+            Twig.debug { "BG Sync: necessary trigger delay time: $targetTimeDiff" }
+
             val constraints =
                 Constraints.Builder()
                     .setRequiresStorageNotLow(true)
-                    .setRequiredNetworkType(NetworkType.CONNECTED)
+                    .setRequiredNetworkType(NetworkType.UNMETERED)
```
Comment (nuttycom) [inline ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt:83]: One question; since this is a change to an existing method, doesn't this mean that this now makes it that sync can _only_ happen on wifi and while charging?

**Review by nuttycom — CHANGES_REQUESTED** [review]
Can you confirm that after this change, that it's still possible to sync normally, i.e. if I'm in the coffee shop and open my wallet, it will complete the sync to the chain tip from the last time my wallet synced in the background?

Marking as changes requested pending the answer to this question.

File: ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt (hunk 1 above)
Comment (HonzaR) [reply ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt:83]: The existing solution of background syncing wasn't working as expected (see #634) and had a problem with its triggering because of the `it.progress.isLessThanHundredPercent()` condition, although it was enabled for users. These issues are now fixed.

**Comment by HonzaR** [comment]
> Can you confirm that after this change, that it's still possible to sync normally, i.e. if I'm in the coffee shop and open my wallet, it will complete the sync to the chain tip from the last time my wallet synced in the background?

Yes, this is definitely a different case from the regular foreground syncing. This one is triggered from the background via `SyncWorker` that calls `WalletCoordinator` inside it. The foreground sync path is calling the same `WalletCoordinator` component but from the ViewModel, which is called from UI. So those are separated and not related sync paths.

**Review by nuttycom — APPROVED** [review]
utACK b1c457bc113edc9d58fb4ad1425bfeec773dcb6f

File: ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt [hunk 2]
```diff
@@ -12,55 +12,115 @@ import cash.z.ecc.android.sdk.Synchronizer
...
+                    .setRequiresCharging(true)
                     .build()
 
-            return PeriodicWorkRequestBuilder<SyncWorker>(DEFAULT_SYNC_PERIOD.toJavaDuration())
+            return PeriodicWorkRequestBuilder<SyncWorker>(SYNC_PERIOD.toJavaDuration())
```
Comment (str4d) [inline ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt:87]: The documentation for this constructor says:
> The [`PeriodicWorkRequest`](https://developer.android.com/reference/androidx/work/PeriodicWorkRequest) is guaranteed to run exactly one time during this interval (subject to OS battery optimizations, such as doze mode). [..] It may run immediately, at the end of the period, or any time in between so long as the other conditions are satisfied at the time.

AFAICT this means that the interval will start at some time `X` between 3am and 4am (due to `setInitialDelay`), but that `SyncWorker` can be triggered at any time between `X` and `X + SYNC_PERIOD` (i.e. it could sync at 2pm, if `constraints` happen to be met at that time). Is this the intended behaviour? I don't know how likely it is that jobs are always run at the beginning of their interval.

If we actually want to require that the background sync only be triggered to start between 3am and 4am, then the alternative "flex period" constructor would be more suitable: we'd set the interval to start at 4am, with a 1 hour `flexInterval` so that the flex perid is 3-4am (`repeatInterval - flexInterval` to the end of the interval, per the docs).

**Review by str4d — APPROVED** [review]
utACK b1c457bc113edc9d58fb4ad1425bfeec773dcb6f, with a question about how the background work is scheduled.

File: ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt (hunk 2 above)
Comment (str4d) [reply ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt:87]: A side-effect of using the flex period would be that the first background sync would be on the second night after first installing the app (as we can only shift the start point of the interval with `setInitialDelay`, and the flex period is the last `flexInterval` of the interval). But maybe there's a way around that by also scheduling a one-off task for the first night.

Comment (HonzaR) [reply ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt:87]: Thanks for pointing this out. Yes, I was aware of the `flexInterval` when implementing this. It is one option to consider for our use case. The "second night" drawback was something that I didn't know how to by-pass, and from my experience and testing, the trigger usually happened at the beginning of the `repeatInterval` as we have limited it with the **unmetered connection** and **is plugged into the power** constraints under which is the system in a perfect position to start any planned worker. 

My second thought is that we might have only some of the users having their devices plugged in and on wifi at night, so the trigger for those will start once these constraints are met, and that could be at any time during the day. Thus, the 3-4 a.m. requirement would not be met, but the main goal of a regular sync will be met.

We can still file a follow-up and revisit the sync planning again. What do you think?

Comment (str4d) [reply ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt:87]: As long as we anticipate user feedback of the form "my wallet isn't syncing" because the sync process is getting triggered when their phone is plugged in for a short time during the day, instead of for a long time at night, then I think this is fine to merge as-is and we can revisit this later if needed.

Comment (HonzaR) [reply ui-lib/src/main/java/co/electriccoin/zcash/work/SyncWorker.kt:87]: Filed #1258.
